[package]
name = "chat"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rand = "0.8"
async-trait = "0.1"
azure_data_cosmos = "0.1"
thiserror = "1.0"
